import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { AppButton } from '../../components/ui/AppButton';
import { AppHeader } from '../../components/ui/AppHeader';
import { BottomSheet } from '../../components/ui/BottomSheet';
import { Screen } from '../../components/ui/Screen';
import { getErrorMessage } from '../../services/api/client';
import { getDashboardSnapshot, formatEuro } from '../../services/dashboard/dashboard.service';
import { sellerToolsService, type AdCampaign, type ReferralCampaign, type SellerAnnouncement, type SellerCoupon } from '../../services/seller/tools.service';
import { colors, radius, shadow } from '../../theme/tokens';
import { useAutoRefresh } from '../../hooks/useAutoRefresh';

type Tool = 'coupons' | 'announcements' | 'referrals' | 'boost' | 'statistics' | 'subscription';
const details: Record<Tool, { title: string; icon: React.ComponentProps<typeof MaterialCommunityIcons>['name']; intro: string; add?: string }> = { coupons: { title: 'Coupons', icon: 'ticket-percent-outline', intro: 'Create, schedule and manage customer discount codes.', add: 'Create coupon' }, announcements: { title: 'Announcements', icon: 'bullhorn-outline', intro: 'Publish time-bound store announcements for buyers.', add: 'New announcement' }, referrals: { title: 'Referral campaigns', icon: 'account-supervisor-outline', intro: 'Reserve a budget and reward qualified referrals.', add: 'New referral' }, boost: { title: 'Boost product', icon: 'rocket-launch-outline', intro: 'Reserve wallet budget for higher product visibility.', add: 'Boost a product' }, statistics: { title: 'Statistics', icon: 'chart-box-outline', intro: 'Live business performance for your current store.' }, subscription: { title: 'Subscription', icon: 'card-account-details-outline', intro: 'Review the plan and seller features available to your store.' } };
const readable = (value?: string | null) => (value || '—').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());

export function BusinessToolsScreen() {
  const { tool } = useLocalSearchParams<{ tool?: Tool }>(); const current: Tool = ['coupons', 'announcements', 'referrals', 'boost', 'statistics', 'subscription'].includes(tool ?? '') ? tool as Tool : 'statistics'; const meta = details[current]; const [rows, setRows] = useState<(SellerCoupon | SellerAnnouncement | ReferralCampaign | AdCampaign)[]>([]); const [stats, setStats] = useState<{ label: string; value: string }[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); if (current === 'coupons') setRows(await sellerToolsService.coupons()); else if (current === 'announcements') setRows(await sellerToolsService.announcements()); else if (current === 'referrals') setRows(await sellerToolsService.referrals()); else if (current === 'boost') setRows(await sellerToolsService.boostCampaigns()); else if (current === 'statistics') { const data = await getDashboardSnapshot(); setStats([{ label: 'This month revenue', value: formatEuro(data.monthlyRevenue) }, { label: 'Orders', value: String(data.monthlyOrders) }, { label: 'Products', value: String(data.totalProducts) }, { label: 'Followers', value: String(data.monthlyFollowers) }]); } else { const [currentPlan, plans] = await Promise.all([sellerToolsService.subscription(), sellerToolsService.subscriptionPlans()]); setStats([{ label: 'Current plan', value: currentPlan.plan?.name || currentPlan.subscription?.status || 'No active plan' }, { label: 'Price', value: currentPlan.plan?.price !== undefined ? formatEuro(currentPlan.plan.price) : '—' }, { label: 'Available plans', value: String(plans.plans?.length ?? 0) }]); } } catch (cause) { setError(getErrorMessage(cause)); } finally { setLoading(false); } }, [current]);
  useAutoRefresh(load, true, 15_000, current);
  return <Screen contentStyle={styles.bottom}><AppHeader title={meta.title} left={<MaterialCommunityIcons name="arrow-left" size={22} color="#3E5877" />} onLeftPress={() => router.back()} right={meta.add ? <MaterialCommunityIcons name="plus" size={23} color="#3E5877" /> : null} onRightPress={() => setOpen(true)} /><View style={styles.body}><View style={styles.hero}><View style={styles.heroIcon}><MaterialCommunityIcons name={meta.icon} size={25} color={colors.blue} /></View><View style={{ flex: 1 }}><Text style={styles.heading}>{meta.title}</Text><Text style={styles.copy}>{meta.intro}</Text></View></View>{error ? <View style={styles.error}><Text style={styles.errorText}>{error}</Text></View> : null}{loading ? <State label="Syncing seller data…" /> : stats.length ? <View style={styles.metrics}>{stats.map((item) => <View key={item.label} style={styles.metric}><Text style={styles.metricValue}>{item.value}</Text><Text style={styles.metricLabel}>{item.label}</Text></View>)}</View> : rows.length ? rows.map((row) => <ToolRow key={row.id} tool={current} row={row} refresh={() => void load()} />) : <State label="Nothing is here yet." empty />}</View><ToolCreator visible={open} tool={current} onClose={() => setOpen(false)} onSaved={() => { setOpen(false); void load(); }} /></Screen>;
}

function ToolRow({ tool, row, refresh }: { tool: Tool; row: SellerCoupon | SellerAnnouncement | ReferralCampaign | AdCampaign; refresh: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const title = 'code' in row ? row.code : 'title' in row ? row.title : row.name; const subtitle = 'discount_type' in row ? `${row.discount_value}${row.discount_type === 'percentage' ? '%' : row.discount_type === 'fixed_amount' ? ' fixed' : ' shipping'} · ${readable(row.scope)}` : 'message' in row ? row.message : 'reward_amount' in row ? `${row.reward_amount} ${row.reward_type} · ${readable(row.scope_type)}` : `${row.product?.name || 'Product boost'} · ${readable(row.status)}`; const status = 'is_active' in row ? row.is_active ? 'Active' : 'Inactive' : readable(row.status);
  const act = async (action: 'toggle' | 'pause' | 'resume' | 'delete' | 'archive') => { try { setBusy(true); if (tool === 'coupons') { if (action === 'delete') await sellerToolsService.deleteCoupon(row.id); else if (action === 'toggle') await sellerToolsService.couponAction(row.id, 'toggle-status'); else await sellerToolsService.couponAction(row.id, action === 'pause' ? 'pause' : 'resume'); } else if (tool === 'announcements') { if (action === 'delete') await sellerToolsService.deleteAnnouncement(row.id); else await sellerToolsService.toggleAnnouncement(row.id); } else if (tool === 'referrals') await sellerToolsService.referralAction(row.id, action === 'archive' ? 'archive' : action === 'pause' ? 'pause' : 'resume'); else if (tool === 'boost') await sellerToolsService.boostAction(row.id, action); refresh(); } catch (cause) { setError(getErrorMessage(cause)); } finally { setBusy(false); } };
  return <View style={styles.row}>{error ? <Text style={styles.inlineError}>{error}</Text> : null}<View style={{ flex: 1 }}><Text style={styles.rowTitle}>{title}</Text><Text numberOfLines={2} style={styles.rowText}>{subtitle}</Text><Text style={styles.rowMeta}>{status}</Text></View><View style={styles.rowActions}>{(tool === 'coupons' || tool === 'announcements') ? <Pressable disabled={busy} onPress={() => void act('toggle')}><MaterialCommunityIcons name="eye-outline" size={20} color={colors.blue} /></Pressable> : null}{['active', 'scheduled'].includes(('status' in row ? row.status : '')) ? <Pressable disabled={busy} onPress={() => void act('pause')}><MaterialCommunityIcons name="pause-circle-outline" size={20} color={colors.blue} /></Pressable> : null}{('status' in row && row.status === 'paused') ? <Pressable disabled={busy} onPress={() => void act('resume')}><MaterialCommunityIcons name="play-circle-outline" size={20} color={colors.blue} /></Pressable> : null}<Pressable disabled={busy} onPress={() => void act(tool === 'referrals' ? 'archive' : 'delete')}><MaterialCommunityIcons name="trash-can-outline" size={20} color={colors.red} /></Pressable></View></View>;
}

function ToolCreator({ visible, tool, onClose, onSaved }: { visible: boolean; tool: Tool; onClose: () => void; onSaved: () => void }) {
  const [form, setForm] = useState(() => ({ name: '', code: '', text: '', amount: '10', budget: '50', end: new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10) })); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  if (!details[tool].add) return null;
  const save = async () => { try { setBusy(true); const ends = new Date(`${form.end}T23:59:59`).toISOString(); if (tool === 'coupons') { if (!form.code.trim()) throw new Error('Coupon code is required.'); await sellerToolsService.createCoupon({ code: form.code.trim().toUpperCase(), description: form.text || undefined, discount_type: 'percentage', discount_value: Number(form.amount), scope: 'store', starts_at: new Date().toISOString(), ends_at: ends, launch_mode: 'run_now', is_active: true, is_public: true, followers_only: false, first_order_only: false }); } else if (tool === 'announcements') { if (!form.name.trim() || !form.text.trim()) throw new Error('A title and message are required.'); await sellerToolsService.createAnnouncement({ title: form.name.trim(), message: form.text.trim(), start_date: new Date().toISOString(), end_date: ends, is_active: true }); } else if (tool === 'referrals') { if (!form.name.trim()) throw new Error('Campaign name is required.'); await sellerToolsService.createReferral({ name: form.name.trim(), scope_type: 'store', reward_type: 'percentage', reward_amount: Number(form.amount), budget_amount: Number(form.budget), minimum_quantity: 1, minimum_order_amount: 0, new_customer_only: true, platform_stacking: 'exclusive', activation_mode: 'immediate', starts_at: new Date().toISOString(), ends_at: ends }); } else if (tool === 'boost') { const options = await sellerToolsService.boostOptions(); const product = options.products.data?.[0]; if (!product) throw new Error('There are no eligible, approved products to boost.'); await sellerToolsService.createBoost({ product_id: product.id, name: form.name.trim() || `${product.name} boost`, starts_at: new Date().toISOString(), ends_at: ends, budget_type: 'total', budget_amount: Number(form.budget), bid_type: 'cpc', bid_amount: Math.min(0.5, Number(form.budget)), placements: options.placements.slice(0, 1), locations: ['global'], schedule_timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, launch_mode: 'run_now', idempotency_key: `${Date.now()}-${Math.random().toString(36).slice(2)}` }); } onSaved(); } catch (cause) { setError(getErrorMessage(cause)); } finally { setBusy(false); } };
  return <BottomSheet visible={visible} title={details[tool].add || ''} subtitle="Fields follow the active seller API contract." onClose={onClose}>{error ? <View style={styles.error}><Text style={styles.errorText}>{error}</Text></View> : null}{tool === 'coupons' ? <Field label="Coupon code" value={form.code} onChangeText={(code) => setForm((state) => ({ ...state, code }))} autoCapitalize="characters" /> : <Field label="Name" value={form.name} onChangeText={(name) => setForm((state) => ({ ...state, name }))} />}{tool !== 'boost' ? <Field label={tool === 'announcements' ? 'Message' : 'Description'} value={form.text} onChangeText={(text) => setForm((state) => ({ ...state, text }))} multiline /> : null}{tool !== 'announcements' ? <Field label={tool === 'boost' || tool === 'referrals' ? 'Budget (€)' : 'Percentage off'} value={tool === 'boost' || tool === 'referrals' ? form.budget : form.amount} onChangeText={(value) => setForm((state) => tool === 'boost' || tool === 'referrals' ? { ...state, budget: value } : { ...state, amount: value })} keyboardType="decimal-pad" /> : null}{tool === 'referrals' ? <Field label="Reward percentage" value={form.amount} onChangeText={(amount) => setForm((state) => ({ ...state, amount }))} keyboardType="decimal-pad" /> : null}<Field label="End date (YYYY-MM-DD)" value={form.end} onChangeText={(end) => setForm((state) => ({ ...state, end }))} /><AppButton label={busy ? 'Saving…' : details[tool].add || 'Save'} disabled={busy} onPress={() => void save()} style={styles.save} /></BottomSheet>;
}
function Field({ label, multiline, ...props }: { label: string; multiline?: boolean } & React.ComponentProps<typeof TextInput>) { return <View style={styles.fieldGroup}><Text style={styles.label}>{label}</Text><TextInput multiline={multiline} placeholderTextColor="#7C8BA0" style={[styles.field, multiline && styles.textarea]} {...props} /></View>; }
function State({ label, empty }: { label: string; empty?: boolean }) { return <View style={styles.state}>{empty ? <MaterialCommunityIcons name="folder-open-outline" size={30} color={colors.blue} /> : <ActivityIndicator size="large" color={colors.blue} />}<Text style={styles.copy}>{label}</Text></View>; }
const styles = StyleSheet.create({ bottom: { paddingBottom: 124 }, body: { padding: 20 }, hero: { flexDirection: 'row', gap: 11, alignItems: 'center' }, heroIcon: { width: 47, height: 47, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E7F1FF' }, heading: { color: colors.ink, fontSize: 21, fontWeight: '800', letterSpacing: -.6 }, copy: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 3 }, error: { padding: 10, marginTop: 13, borderRadius: 10, backgroundColor: '#FFF0F1' }, errorText: { color: colors.red, fontSize: 11 }, metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginTop: 16 }, metric: { width: '47%', minHeight: 75, padding: 11, borderRadius: radius.md, backgroundColor: colors.surface, ...shadow.card }, metricValue: { color: colors.ink, fontSize: 17, fontWeight: '800' }, metricLabel: { color: colors.muted, fontSize: 10, marginTop: 4 }, state: { minHeight: 230, justifyContent: 'center', alignItems: 'center', gap: 10 }, row: { minHeight: 78, padding: 11, marginTop: 11, borderRadius: radius.md, backgroundColor: colors.surface, flexDirection: 'row', gap: 10, ...shadow.card }, rowTitle: { color: colors.ink, fontSize: 13, fontWeight: '800' }, rowText: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, rowMeta: { color: colors.blue, fontSize: 10, marginTop: 4, fontWeight: '800' }, rowActions: { alignItems: 'flex-end', justifyContent: 'space-between', gap: 8 }, inlineError: { position: 'absolute', bottom: -18, left: 8, color: colors.red, fontSize: 9 }, fieldGroup: { marginTop: 11 }, label: { color: colors.ink, fontSize: 12, fontWeight: '800', marginBottom: 6 }, field: { minHeight: 47, paddingHorizontal: 12, borderRadius: 11, backgroundColor: colors.surface, color: colors.ink, fontSize: 13, ...shadow.card }, textarea: { minHeight: 82, paddingTop: 11, textAlignVertical: 'top' }, save: { marginTop: 18 },
});
