import { useCallback, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { profileService, type MarketplaceNotification } from '../../services/profile/profile.service';
import { useAuth } from '../../features/auth/AuthContext';
import { useAutoRefresh } from '../../hooks/useAutoRefresh';
import { colors, radius, shadow } from '../../theme/tokens';

function destination(item: MarketplaceNotification) { const context = item.context ?? {}; const order = context.order_id ?? context.store_order_id; const conversation = context.conversation_id ?? context.store_chat_conversation_id; if (item.url?.startsWith('/')) return item.url; if (String(item.type).startsWith('chat.') && conversation) return { pathname: '/message-thread', params: { mode: 'buyers', id: String(conversation) } }; if (String(item.type).startsWith('chat.')) return '/messages'; if (String(item.type).startsWith('order.') && order) return { pathname: '/order-details/[id]', params: { id: String(order) } }; if (String(item.type).startsWith('order.')) return '/orders'; if (String(item.type).startsWith('support.')) return '/support'; if (String(item.type).startsWith('wallet.')) return '/wallet'; if (String(item.type).startsWith('review.')) return '/reviews'; return '/notifications'; }

export function InAppNotificationListener() { const { isAuthenticated } = useAuth(); const seen = useRef(new Set<string>()); const initialized = useRef(false); const [current, setCurrent] = useState<MarketplaceNotification | null>(null); const sync = useCallback(async () => { if (!isAuthenticated) return; const data = await profileService.notifications(); const unread = data.notifications.filter((item) => !item.read_at); if (!initialized.current) { unread.forEach((item) => seen.current.add(item.id)); initialized.current = true; return; } const next = unread.find((item) => !seen.current.has(item.id)); unread.forEach((item) => seen.current.add(item.id)); if (next) setCurrent(next); }, [isAuthenticated]); useAutoRefresh(() => sync().catch(() => undefined), isAuthenticated, 10_000); if (!current) return null; const open = async () => { try { await profileService.markNotificationRead(current.id); } finally { const route = destination(current); setCurrent(null); router.push(route as never); } }; return <View pointerEvents="box-none" style={styles.root}><Pressable onPress={() => void open()} style={styles.toast}><View style={styles.icon}><MaterialCommunityIcons name="bell-ring-outline" size={20} color={colors.blue} /></View><View style={styles.copy}><Text numberOfLines={1} style={styles.title}>{current.title}</Text><Text numberOfLines={2} style={styles.message}>{current.message}</Text></View><Pressable onPress={() => setCurrent(null)} hitSlop={10}><MaterialCommunityIcons name="close" size={18} color="#6A7D93" /></Pressable></Pressable></View>; }
const styles = StyleSheet.create({ root: { position: 'absolute', left: 16, right: 16, top: 58, zIndex: 100 }, toast: { minHeight: 72, padding: 11, borderRadius: radius.md, backgroundColor: '#FFFFFF', flexDirection: 'row', alignItems: 'center', gap: 9, ...shadow.floating }, icon: { height: 38, width: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EAF3FF' }, copy: { flex: 1, minWidth: 0 }, title: { color: colors.ink, fontSize: 12, fontWeight: '800' }, message: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 2 } });
